// ============================================
// CrowdMind AI - Mock Data for Development
// ============================================

import type {
  User,
  Question,
  Prediction,
  LeaderboardEntry,
  PlatformStats,
  Notification,
  Comment,
  DailyQuestion,
  Achievement,
  PricingPlan,
} from '@/types';

export const mockUsers: User[] = [
  {
    id: 'u1',
    username: 'alexchen',
    displayName: 'Alex Chen',
    email: 'alex@example.com',
    avatar: '',
    reputation: 12450,
    level: 28,
    badge: 'oracle',
    totalVotes: 3420,
    totalQuestions: 89,
    totalPredictions: 156,
    predictionAccuracy: 78.5,
    streak: 14,
    joinedAt: '2025-06-15',
    isPremium: true,
  },
  {
    id: 'u2',
    username: 'sarakim',
    displayName: 'Sara Kim',
    email: 'sara@example.com',
    avatar: '',
    reputation: 9870,
    level: 22,
    badge: 'expert',
    totalVotes: 2890,
    totalQuestions: 45,
    totalPredictions: 98,
    predictionAccuracy: 72.3,
    streak: 7,
    joinedAt: '2025-08-22',
    isPremium: true,
  },
  {
    id: 'u3',
    username: 'mikejohnson',
    displayName: 'Mike Johnson',
    email: 'mike@example.com',
    avatar: '',
    reputation: 6540,
    level: 15,
    badge: 'contributor',
    totalVotes: 1560,
    totalQuestions: 23,
    totalPredictions: 67,
    predictionAccuracy: 65.8,
    streak: 3,
    joinedAt: '2025-10-01',
    isPremium: false,
  },
  {
    id: 'u4',
    username: 'emilydavis',
    displayName: 'Emily Davis',
    email: 'emily@example.com',
    avatar: '',
    reputation: 15200,
    level: 32,
    badge: 'legend',
    totalVotes: 4200,
    totalQuestions: 112,
    totalPredictions: 201,
    predictionAccuracy: 82.1,
    streak: 21,
    joinedAt: '2025-03-10',
    isPremium: true,
  },
  {
    id: 'u5',
    username: 'jameswilson',
    displayName: 'James Wilson',
    email: 'james@example.com',
    avatar: '',
    reputation: 3200,
    level: 9,
    badge: 'newcomer',
    totalVotes: 780,
    totalQuestions: 12,
    totalPredictions: 34,
    predictionAccuracy: 58.2,
    streak: 1,
    joinedAt: '2026-01-15',
    isPremium: false,
  },
];

const OPTION_COLORS = [
  '#6366f1',
  '#f59e0b',
  '#10b981',
  '#ef4444',
  '#8b5cf6',
  '#06b6d4',
];

export const mockQuestions: Question[] = [
  {
    id: 'q1',
    userId: 'u1',
    user: mockUsers[0],
    title: 'Should startups focus on AI-first products in 2026?',
    description:
      'With AI becoming mainstream, should new startups build AI-native products or integrate AI into existing solutions?',
    category: 'business',
    options: [
      { id: 'o1', text: 'Yes, AI-first is the future', votes: 8420, percentage: 62, color: OPTION_COLORS[0] },
      { id: 'o2', text: 'No, focus on real problems first', votes: 3240, percentage: 24, color: OPTION_COLORS[1] },
      { id: 'o3', text: 'Hybrid approach is best', votes: 1900, percentage: 14, color: OPTION_COLORS[2] },
    ],
    totalVotes: 13560,
    totalComments: 342,
    aiAnalysis: {
      summary:
        'The majority favors AI-first approach, but there is a strong minority advocating for problem-first thinking. The hybrid approach is gaining traction.',
      sentiment: 'positive',
      confidence: 87,
      insights: [
        'Tech professionals overwhelmingly support AI-first (78%)',
        'Business founders prefer hybrid approach (45%)',
        'Sentiment has shifted 12% toward AI-first in the last month',
        'Similar questions show consistent pro-AI trend globally',
      ],
      recommendation:
        'Consider an AI-enhanced approach: solve a real problem but leverage AI as a core differentiator.',
      demographics: [
        { label: '18-24', value: 72 },
        { label: '25-34', value: 65 },
        { label: '35-44', value: 58 },
        { label: '45+', value: 41 },
      ],
      trendDirection: 'up',
    },
    tags: ['startup', 'AI', 'strategy', 'tech'],
    status: 'trending',
    visibility: 'public',
    createdAt: '2026-03-10T10:00:00Z',
    expiresAt: '2026-04-10T10:00:00Z',
    image: 'https://picsum.photos/seed/ai-startup/800/400',
    trendData: [45, 48, 52, 55, 60, 63, 67],
    volume24h: 3400,
    changePercent: 5.2,
  },
  {
    id: 'q2',
    userId: 'u2',
    user: mockUsers[1],
    title: 'Which programming language will dominate in 2027?',
    description: 'As the tech landscape evolves, which language will be most in-demand?',
    category: 'technology',
    options: [
      { id: 'o1', text: 'Python', votes: 12300, percentage: 38, color: OPTION_COLORS[0] },
      { id: 'o2', text: 'TypeScript', votes: 9800, percentage: 30, color: OPTION_COLORS[1] },
      { id: 'o3', text: 'Rust', votes: 5200, percentage: 16, color: OPTION_COLORS[2] },
      { id: 'o4', text: 'Go', votes: 3100, percentage: 10, color: OPTION_COLORS[3] },
      { id: 'o5', text: 'Other', votes: 1900, percentage: 6, color: OPTION_COLORS[4] },
    ],
    totalVotes: 32300,
    totalComments: 891,
    aiAnalysis: {
      summary:
        'Python maintains its lead driven by AI/ML dominance. TypeScript continues strong growth in web development.',
      sentiment: 'neutral',
      confidence: 79,
      insights: [
        'Python leads due to AI/ML ecosystem',
        'TypeScript growing fastest year-over-year',
        'Rust gaining in systems programming',
        'Go stable in cloud-native development',
      ],
      trendDirection: 'stable',
    },
    tags: ['programming', 'tech', 'career'],
    status: 'trending',
    visibility: 'public',
    createdAt: '2026-03-12T14:00:00Z',
    image: 'https://picsum.photos/seed/programming/800/400',
    trendData: [50, 52, 51, 54, 56, 55, 58],
    volume24h: 4800,
    changePercent: 2.8,
  },
  {
    id: 'q3',
    userId: 'u4',
    user: mockUsers[3],
    title: 'Is remote work still the future or are companies returning to office?',
    description:
      'Many big tech companies are pushing RTO policies. What does the crowd think about the future of work?',
    category: 'business',
    options: [
      { id: 'o1', text: 'Fully remote is the future', votes: 15600, percentage: 42, color: OPTION_COLORS[0] },
      { id: 'o2', text: 'Hybrid will win', votes: 14200, percentage: 38, color: OPTION_COLORS[1] },
      { id: 'o3', text: 'Back to office', votes: 4800, percentage: 13, color: OPTION_COLORS[2] },
      { id: 'o4', text: 'Depends on industry', votes: 2600, percentage: 7, color: OPTION_COLORS[3] },
    ],
    totalVotes: 37200,
    totalComments: 1203,
    aiAnalysis: {
      summary: 'Remote and hybrid work dominate preference. Office return is a minority view, mostly from enterprise sector.',
      sentiment: 'positive',
      confidence: 84,
      insights: [
        'Developers strongly prefer remote (68%)',
        'Managers lean toward hybrid (52%)',
        'Gen Z surprisingly favors hybrid over full remote',
        'Industries with physical presence needs show different patterns',
      ],
      recommendation: 'Hybrid offers the best balance. Full remote works for tech, but hybrid captures broader talent.',
      demographics: [
        { label: '18-24', value: 48 },
        { label: '25-34', value: 62 },
        { label: '35-44', value: 55 },
        { label: '45+', value: 38 },
      ],
      trendDirection: 'stable',
    },
    tags: ['work', 'remote', 'career', 'office'],
    status: 'active',
    visibility: 'public',
    createdAt: '2026-03-08T09:00:00Z',
    image: 'https://picsum.photos/seed/remote-work/800/400',
    trendData: [60, 58, 55, 53, 52, 50, 48],
    volume24h: 2900,
    changePercent: -2.1,
  },
  {
    id: 'q4',
    userId: 'u3',
    user: mockUsers[2],
    title: 'Which design trend will dominate in 2026?',
    description: 'From glassmorphism to neubrutalism — what design trend do you think will be most popular?',
    category: 'design',
    options: [
      { id: 'o1', text: 'AI-generated UI', votes: 5400, percentage: 35, color: OPTION_COLORS[0] },
      { id: 'o2', text: '3D immersive', votes: 4100, percentage: 27, color: OPTION_COLORS[1] },
      { id: 'o3', text: 'Minimalism 2.0', votes: 3200, percentage: 21, color: OPTION_COLORS[2] },
      { id: 'o4', text: 'Retro/Y2K revival', votes: 2600, percentage: 17, color: OPTION_COLORS[3] },
    ],
    totalVotes: 15300,
    totalComments: 456,
    aiAnalysis: {
      summary: 'AI-generated UI is emerging as the top choice among designers. Traditional minimalism is evolving with AI integration.',
      sentiment: 'positive',
      confidence: 73,
      insights: [
        'AI-generated UI growing 200% month-over-month in discussion',
        '3D immersive popular among game/entertainment designers',
        'Minimalism 2.0 favored for SaaS and enterprise',
        'Retro/Y2K driven by Gen Z social media influence',
      ],
      trendDirection: 'up',
    },
    tags: ['design', 'UI', 'trends'],
    status: 'active',
    visibility: 'public',
    createdAt: '2026-03-11T16:00:00Z',
    image: 'https://picsum.photos/seed/design-trends/800/400',
    trendData: [30, 35, 40, 48, 55, 62, 70],
    volume24h: 1800,
    changePercent: 12.8,
  },
  {
    id: 'q5',
    userId: 'u1',
    user: mockUsers[0],
    title: 'Should I invest in Bitcoin or Ethereum in 2026?',
    description: 'With the crypto market stabilizing, which is the better long-term investment?',
    category: 'finance',
    options: [
      { id: 'o1', text: 'Bitcoin (BTC)', votes: 18900, percentage: 45, color: OPTION_COLORS[0] },
      { id: 'o2', text: 'Ethereum (ETH)', votes: 15200, percentage: 36, color: OPTION_COLORS[1] },
      { id: 'o3', text: 'Both equally', votes: 5400, percentage: 13, color: OPTION_COLORS[2] },
      { id: 'o4', text: 'Neither', votes: 2500, percentage: 6, color: OPTION_COLORS[3] },
    ],
    totalVotes: 42000,
    totalComments: 2100,
    aiAnalysis: {
      summary: 'Bitcoin leads as store-of-value. Ethereum preferred for ecosystem utility. Diversification is the safest strategy.',
      sentiment: 'mixed',
      confidence: 71,
      insights: [
        'Bitcoin dominance correlated with macro uncertainty',
        'Ethereum ecosystem growth driving long-term value',
        'DeFi users strongly prefer ETH (72%)',
        'Institutional investors lean Bitcoin (64%)',
      ],
      recommendation: 'Dollar-cost averaging into both provides the best risk-adjusted return based on historical data.',
      demographics: [
        { label: '18-24', value: 55 },
        { label: '25-34', value: 68 },
        { label: '35-44', value: 42 },
        { label: '45+', value: 25 },
      ],
      trendDirection: 'up',
    },
    tags: ['crypto', 'investment', 'bitcoin', 'ethereum'],
    status: 'trending',
    visibility: 'public',
    createdAt: '2026-03-09T12:00:00Z',
    image: 'https://picsum.photos/seed/bitcoin/800/400',
    trendData: [40, 44, 42, 50, 55, 53, 58],
    volume24h: 7600,
    changePercent: 8.4,
  },
  {
    id: 'q6',
    userId: 'u5',
    user: mockUsers[4],
    title: 'Which logo design looks more professional?',
    description: 'I am launching a SaaS product and need community feedback on the logo.',
    category: 'design',
    options: [
      { id: 'o1', text: 'Option A — Minimalist', votes: 2340, percentage: 58, color: OPTION_COLORS[0] },
      { id: 'o2', text: 'Option B — Bold & Colorful', votes: 1690, percentage: 42, color: OPTION_COLORS[1] },
    ],
    totalVotes: 4030,
    totalComments: 89,
    tags: ['logo', 'design', 'branding'],
    status: 'active',
    visibility: 'public',
    createdAt: '2026-03-14T08:00:00Z',
    image: 'https://picsum.photos/seed/logo/800/400',
    trendData: [20, 25, 30, 38, 45, 52, 58],
    volume24h: 1200,
    changePercent: 15.3,
  },
  {
    id: 'q7',
    userId: 'u2',
    user: mockUsers[1],
    title: 'Will AGI be achieved by 2030?',
    description: 'With rapid progress in AI, do you think we will reach Artificial General Intelligence within the next 4 years?',
    category: 'technology',
    options: [
      { id: 'o1', text: 'Yes, very likely', votes: 9200, percentage: 31, color: OPTION_COLORS[0] },
      { id: 'o2', text: 'Possible but not probable', votes: 11400, percentage: 38, color: OPTION_COLORS[1] },
      { id: 'o3', text: 'No, at least a decade away', votes: 6800, percentage: 23, color: OPTION_COLORS[2] },
      { id: 'o4', text: 'AGI is not well-defined', votes: 2400, percentage: 8, color: OPTION_COLORS[3] },
    ],
    totalVotes: 29800,
    totalComments: 1567,
    aiAnalysis: {
      summary: 'The crowd is cautiously optimistic. Most believe AGI is possible but timeline is debated. Definition ambiguity adds noise.',
      sentiment: 'neutral',
      confidence: 68,
      insights: [
        'AI researchers are more skeptical than the general public',
        'Timeline estimates vary widely by expertise level',
        'Definition of AGI is a major point of contention',
        'Recent breakthroughs have shifted sentiment positively',
      ],
      trendDirection: 'up',
    },
    tags: ['AGI', 'AI', 'future', 'technology'],
    status: 'trending',
    visibility: 'public',
    createdAt: '2026-03-13T11:00:00Z',
    image: 'https://picsum.photos/seed/agi/800/400',
    trendData: [35, 38, 42, 45, 50, 55, 62],
    volume24h: 5200,
    changePercent: 9.7,
  },
  {
    id: 'q8',
    userId: 'u4',
    user: mockUsers[3],
    title: 'Best country to launch a tech startup in 2026?',
    description: 'Considering regulations, talent pool, funding availability, and ecosystem support.',
    category: 'business',
    options: [
      { id: 'o1', text: 'United States', votes: 14500, percentage: 35, color: OPTION_COLORS[0] },
      { id: 'o2', text: 'Singapore', votes: 8300, percentage: 20, color: OPTION_COLORS[1] },
      { id: 'o3', text: 'UAE (Dubai)', votes: 7200, percentage: 17, color: OPTION_COLORS[2] },
      { id: 'o4', text: 'UK', votes: 5900, percentage: 14, color: OPTION_COLORS[3] },
      { id: 'o5', text: 'Estonia', votes: 3800, percentage: 9, color: OPTION_COLORS[4] },
      { id: 'o6', text: 'Other', votes: 2100, percentage: 5, color: OPTION_COLORS[5] },
    ],
    totalVotes: 41800,
    totalComments: 987,
    tags: ['startup', 'entrepreneurship', 'global'],
    status: 'active',
    visibility: 'public',
    createdAt: '2026-03-07T15:00:00Z',
    image: 'https://picsum.photos/seed/startup-country/800/400',
    trendData: [55, 52, 50, 48, 47, 45, 43],
    volume24h: 2100,
    changePercent: -3.5,
  },
];

export const mockPredictions: Prediction[] = [
  {
    id: 'p1',
    userId: 'u1',
    user: mockUsers[0],
    title: 'Bitcoin price on April 1, 2026',
    description: 'What will be the price of Bitcoin on April 1st?',
    category: 'crypto',
    currentValue: 95420,
    targetDate: '2026-04-01',
    options: [
      { id: 'po1', text: 'Below $80K', odds: 3.5, participants: 1200 },
      { id: 'po2', text: '$80K - $100K', odds: 1.8, participants: 4500 },
      { id: 'po3', text: '$100K - $120K', odds: 2.1, participants: 3200 },
      { id: 'po4', text: 'Above $120K', odds: 4.2, participants: 890 },
    ],
    totalParticipants: 9790,
    status: 'open',
    prize: 5000,
    createdAt: '2026-03-01T00:00:00Z',
    image: 'https://picsum.photos/seed/bitcoin-price/800/400',
    trendData: [40, 45, 50, 48, 55, 60, 65],
    changePercent: 7.2,
  },
  {
    id: 'p2',
    userId: 'u4',
    user: mockUsers[3],
    title: 'Will Apple release AR glasses in 2026?',
    description: 'Apple has been rumored to release lightweight AR glasses this year.',
    category: 'tech',
    targetDate: '2026-12-31',
    options: [
      { id: 'po1', text: 'Yes, before Q3', odds: 5.0, participants: 2100 },
      { id: 'po2', text: 'Yes, Q4', odds: 2.5, participants: 3400 },
      { id: 'po3', text: 'No, delayed to 2027', odds: 1.9, participants: 4200 },
    ],
    totalParticipants: 9700,
    status: 'open',
    prize: 3000,
    createdAt: '2026-02-15T00:00:00Z',
    image: 'https://picsum.photos/seed/apple-glasses/800/400',
    trendData: [25, 28, 32, 35, 38, 40, 42],
    changePercent: 3.8,
  },
  {
    id: 'p3',
    userId: 'u2',
    user: mockUsers[1],
    title: 'Champions League 2026 Winner',
    description: 'Which team will win the UEFA Champions League?',
    category: 'sports',
    targetDate: '2026-06-01',
    options: [
      { id: 'po1', text: 'Real Madrid', odds: 2.8, participants: 5600 },
      { id: 'po2', text: 'Manchester City', odds: 3.1, participants: 4200 },
      { id: 'po3', text: 'Bayern Munich', odds: 4.5, participants: 2800 },
      { id: 'po4', text: 'PSG', odds: 5.2, participants: 1900 },
      { id: 'po5', text: 'Other', odds: 3.0, participants: 3100 },
    ],
    totalParticipants: 17600,
    status: 'open',
    prize: 10000,
    createdAt: '2026-01-10T00:00:00Z',
    image: 'https://picsum.photos/seed/champions-league/800/400',
    trendData: [30, 35, 38, 42, 45, 48, 52],
    changePercent: 6.1,
  },
  {
    id: 'p4',
    userId: 'u3',
    user: mockUsers[2],
    title: 'Global AI regulation by end of 2026?',
    description: 'Will there be a binding international AI regulation framework?',
    category: 'politics',
    targetDate: '2026-12-31',
    options: [
      { id: 'po1', text: 'Yes, comprehensive', odds: 6.0, participants: 1800 },
      { id: 'po2', text: 'Partial framework', odds: 2.0, participants: 5200 },
      { id: 'po3', text: 'No global agreement', odds: 2.2, participants: 4100 },
    ],
    totalParticipants: 11100,
    status: 'open',
    createdAt: '2026-02-01T00:00:00Z',
    image: 'https://picsum.photos/seed/ai-regulation/800/400',
    trendData: [45, 42, 38, 35, 33, 30, 28],
    changePercent: -4.5,
  },
];

export const mockLeaderboard: LeaderboardEntry[] = [
  { rank: 1, user: mockUsers[3], score: 15200, accuracy: 82.1, streak: 21, change: 0 },
  { rank: 2, user: mockUsers[0], score: 12450, accuracy: 78.5, streak: 14, change: 1 },
  { rank: 3, user: mockUsers[1], score: 9870, accuracy: 72.3, streak: 7, change: -1 },
  { rank: 4, user: mockUsers[2], score: 6540, accuracy: 65.8, streak: 3, change: 2 },
  { rank: 5, user: mockUsers[4], score: 3200, accuracy: 58.2, streak: 1, change: 0 },
];

export const mockStats: PlatformStats = {
  totalUsers: 284500,
  totalQuestions: 45200,
  totalVotes: 12800000,
  totalPredictions: 8900,
  activeNow: 3420,
  questionsToday: 127,
};

export const mockNotifications: Notification[] = [
  { id: 'n1', type: 'vote', title: 'Your question is trending!', message: '"Should startups focus on AI-first?" has received 1,000+ new votes', read: false, createdAt: '2026-03-15T08:30:00Z', link: '/questions/q1' },
  { id: 'n2', type: 'achievement', title: 'Achievement Unlocked!', message: 'You earned "Oracle" badge for 75%+ prediction accuracy', read: false, createdAt: '2026-03-15T07:00:00Z' },
  { id: 'n3', type: 'prediction', title: 'Prediction resolved', message: 'Bitcoin price prediction ended — check your results!', read: false, createdAt: '2026-03-14T22:00:00Z', link: '/predictions' },
  { id: 'n4', type: 'comment', title: 'New comment on your question', message: 'Sara Kim commented on "Should I invest in Bitcoin or Ethereum?"', read: true, createdAt: '2026-03-14T18:00:00Z', link: '/questions/q5' },
  { id: 'n5', type: 'system', title: 'Welcome to CrowdMind AI!', message: 'Start by asking your first question or making a prediction', read: true, createdAt: '2026-03-14T12:00:00Z' },
  { id: 'n6', type: 'vote', title: '500 votes milestone', message: '"Which programming language will dominate?" hit 32K votes', read: true, createdAt: '2026-03-13T16:00:00Z', link: '/questions/q2' },
];

export const mockComments: Comment[] = [
  { id: 'c1', userId: 'u2', user: mockUsers[1], questionId: 'q1', text: 'AI-first makes sense if the problem inherently benefits from AI. Otherwise you are just adding complexity.', likes: 124, createdAt: '2026-03-10T12:00:00Z' },
  { id: 'c2', userId: 'u4', user: mockUsers[3], questionId: 'q1', text: 'The hybrid approach wins every time. Build for the problem, enhance with AI. That is what the best startups do.', likes: 98, createdAt: '2026-03-10T14:30:00Z' },
  { id: 'c3', userId: 'u3', user: mockUsers[2], questionId: 'q1', text: 'Depends on the market. B2B? AI-first. B2C? Problem-first.', likes: 67, createdAt: '2026-03-11T09:00:00Z' },
  { id: 'c4', userId: 'u5', user: mockUsers[4], questionId: 'q1', text: 'As a newcomer, I find the AI-first hype overblown. Solve a real pain point first.', likes: 45, createdAt: '2026-03-12T16:00:00Z' },
  { id: 'c5', userId: 'u1', user: mockUsers[0], questionId: 'q1', text: 'Great discussion! The data shows 62% AI-first, but the nuance is in the comments.', likes: 89, createdAt: '2026-03-13T10:00:00Z' },
];

export const mockDailyQuestions: DailyQuestion[] = [
  { id: 'dq1', title: 'AI vs. Humans: Will Machines Replace 50% of Jobs by 2035?', description: 'The great automation debate — cast your vote and earn bonus XP!', category: 'technology', xpReward: 50, expiresAt: '2026-03-15T23:59:59Z' },
  { id: 'dq2', title: 'TikTok, Threads, or X? The Ultimate Marketing Platform Showdown', description: 'Which platform delivers the best ROI for brands in 2026? Help the community decide!', category: 'business', xpReward: 30, expiresAt: '2026-03-15T23:59:59Z' },
  { id: 'dq3', title: 'Should Every University Student Be Required to Learn AI?', description: 'A hot education policy debate — weigh in and shape the future of learning!', category: 'education', xpReward: 40, expiresAt: '2026-03-15T23:59:59Z' },
];

export const mockAchievements: Achievement[] = [
  { id: 'a1', icon: '🚀', title: 'First Vote', description: 'Cast your first vote on a question', unlocked: true, unlockedAt: '2025-06-15', xpReward: 10, rarity: 'common' },
  { id: 'a2', icon: '🧠', title: 'Question Master', description: 'Ask 10 questions that get 1000+ votes', unlocked: true, unlockedAt: '2025-09-20', xpReward: 200, rarity: 'rare' },
  { id: 'a3', icon: '🎯', title: 'Sharp Shooter', description: '10 correct predictions in a row', unlocked: true, unlockedAt: '2025-11-05', xpReward: 500, rarity: 'epic' },
  { id: 'a4', icon: '🔥', title: 'On Fire', description: '7 day voting streak', unlocked: true, unlockedAt: '2026-01-10', xpReward: 100, rarity: 'rare' },
  { id: 'a5', icon: '💎', title: 'Diamond Mind', description: 'Reach 10,000 reputation points', unlocked: true, unlockedAt: '2026-02-28', xpReward: 1000, rarity: 'legendary' },
  { id: 'a6', icon: '👑', title: 'Oracle', description: '80% prediction accuracy over 100+ predictions', unlocked: false, xpReward: 2000, rarity: 'legendary' },
  { id: 'a7', icon: '🌍', title: 'Global Voice', description: 'Get votes from 50+ countries on a single question', unlocked: false, xpReward: 500, rarity: 'epic' },
  { id: 'a8', icon: '⚡', title: 'Speed Voter', description: 'Vote on 100 questions in a single day', unlocked: false, xpReward: 150, rarity: 'rare' },
  { id: 'a9', icon: '🏆', title: 'Leaderboard Champion', description: 'Reach #1 on the global leaderboard', unlocked: false, xpReward: 5000, rarity: 'legendary' },
  { id: 'a10', icon: '🤝', title: 'Community Builder', description: 'Refer 25 friends who become active users', unlocked: false, xpReward: 750, rarity: 'epic' },
];

export const mockPricingPlans: PricingPlan[] = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    period: 'monthly',
    features: [
      '5 questions per day',
      'Basic voting',
      '3 predictions per week',
      'Community access',
      'Basic AI insights',
    ],
    highlighted: false,
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 9.99,
    period: 'monthly',
    features: [
      'Unlimited questions',
      'Priority visibility',
      'Unlimited predictions',
      'Full AI analysis reports',
      'Demographic insights',
      'Export data (CSV/PDF)',
      'Custom branding on questions',
      'Remove ads',
      'Priority support',
    ],
    highlighted: true,
    badge: 'Most Popular',
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 49.99,
    period: 'monthly',
    features: [
      'Everything in Pro',
      'Sponsored questions',
      'API access',
      'Custom analytics dashboard',
      'Dedicated account manager',
      'White-label solution',
      'Advanced trend reports',
      'Team collaboration',
      'SLA guarantee',
      'Custom integrations',
    ],
    highlighted: false,
    badge: 'For Teams',
  },
];

export const categories: { value: string; label: string; icon: string; color: string }[] = [
  { value: 'business', label: 'Business', icon: '💼', color: '#6366f1' },
  { value: 'technology', label: 'Technology', icon: '💻', color: '#06b6d4' },
  { value: 'design', label: 'Design', icon: '🎨', color: '#f59e0b' },
  { value: 'lifestyle', label: 'Lifestyle', icon: '🌟', color: '#10b981' },
  { value: 'finance', label: 'Finance', icon: '📈', color: '#8b5cf6' },
  { value: 'sports', label: 'Sports', icon: '⚽', color: '#ef4444' },
  { value: 'politics', label: 'Politics', icon: '🏛️', color: '#64748b' },
  { value: 'entertainment', label: 'Entertainment', icon: '🎬', color: '#ec4899' },
  { value: 'education', label: 'Education', icon: '📚', color: '#14b8a6' },
  { value: 'health', label: 'Health', icon: '🏥', color: '#22c55e' },
];

export const featuredMarkets = [
  {
    id: 'fm1',
    title: 'Will GPT-5 Launch Before July 2026?',
    image: 'https://picsum.photos/seed/gpt5-launch/800/400',
    yesPercent: 72,
    totalVotes: 89400,
    volume24h: 12800,
    changePercent: 8.3,
    trendData: [35, 42, 48, 55, 62, 68, 72],
    category: 'technology',
    hot: true,
  },
  {
    id: 'fm2',
    title: 'Bitcoin Above $150K by End of 2026?',
    image: 'https://picsum.photos/seed/bitcoin-150k/800/400',
    yesPercent: 34,
    totalVotes: 156000,
    volume24h: 24500,
    changePercent: -3.2,
    trendData: [45, 42, 38, 40, 36, 35, 34],
    category: 'finance',
    hot: true,
  },
  {
    id: 'fm3',
    title: 'Tesla Stock Over $500 by Q3 2026?',
    image: 'https://picsum.photos/seed/tesla-stock/800/400',
    yesPercent: 58,
    totalVotes: 67200,
    volume24h: 8900,
    changePercent: 4.1,
    trendData: [40, 45, 50, 48, 52, 55, 58],
    category: 'finance',
    hot: false,
  },
  {
    id: 'fm4',
    title: 'Will Apple Release AR Glasses in 2026?',
    image: 'https://picsum.photos/seed/apple-ar/800/400',
    yesPercent: 41,
    totalVotes: 43800,
    volume24h: 5600,
    changePercent: 2.7,
    trendData: [30, 32, 35, 38, 37, 40, 41],
    category: 'technology',
    hot: false,
  },
  {
    id: 'fm5',
    title: 'Global AI Regulation Before 2027?',
    image: 'https://picsum.photos/seed/ai-regulation/800/400',
    yesPercent: 23,
    totalVotes: 31200,
    volume24h: 4200,
    changePercent: -1.5,
    trendData: [30, 28, 26, 25, 24, 23, 23],
    category: 'politics',
    hot: false,
  },
  {
    id: 'fm6',
    title: 'Champions League 2026: Real Madrid Wins?',
    image: 'https://picsum.photos/seed/champions-league/800/400',
    yesPercent: 45,
    totalVotes: 92100,
    volume24h: 15300,
    changePercent: 6.8,
    trendData: [28, 32, 35, 38, 40, 43, 45],
    category: 'sports',
    hot: true,
  },
];
